# Generated by Django 5.1.6 on 2025-05-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_photo_rename_author_comment_user_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
