# Generated by Django 5.1.6 on 2025-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'The draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
